version: '3.4'

services:
  mongodb:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"
      - "27018:27018"

  mssql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "somepassword.01"
      ACCEPT_EULA: "Y"
    ports:
      - "3306:3306"

  medicinemanaging.api:
    image: ${DOCKER_REGISTRY-}medicinemanagingapi
    build:
      context: .
      dockerfile: MedicineManaging.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:80;http://+:443"
    ports:
      - "10001:80"
      - "10000:443"
    depends_on:
      - mongodb

  usermanaging.api:
    image: ${DOCKER_REGISTRY-}usermanagingapi
    build:
      context: .
      dockerfile: MedicalResearch/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:80;http://+:443"
    ports:
      - "9000:80"
      - "9001:443"
    depends_on:
      - mssql