version: '3.4'

services:
  mongodb:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"
      - "27018:27018"

  mssql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "somepassword.01"
      ACCEPT_EULA: "Y"
    ports:
      - "3306:3306"

  medicinemanaging.api:
    image: ${DOCKER_REGISTRY-}medicinemanagingapi
    build:
      context: .
      dockerfile: MedicineManaging.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:80;http://+:443"
    volumes:
      - ./Https:/root/.aspnet/https:ro
      - ./UserSecrets:/root/.microsoft/usersecrets:ro
    ports:
      - "10000:80"
      - "10001:443"
    depends_on:
      - mongodb
    # secrets:
    #  - external_secret
    #  - medicinemanagingapi_secret

  usermanaging.api:
    image: ${DOCKER_REGISTRY-}usermanagingapi
    build:
      context: .
      dockerfile: MedicalResearch/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:80;http://+:443"
    volumes:
      - ./Https:/root/.aspnet/https:ro
      - ./UserSecrets:/root/.microsoft/usersecrets:ro
    ports:
      - "9000:80"
      - "9001:443"
    depends_on:
      - mssql
    # secrets:
    #  - external_secret
    #  - usermanagingapi_secret
    
secrets:
  external_secret:
    external: true
  usermanagingapi_secret:
    file: usermanagingapi_secret.json
  medicinemanagingapi_secret:
    file: medicinemanagingapi_secret.json